### ISSUE TITLE
Use file globs for cli

### ISSUE THREAD

**Issue by pspeter3** [vvakame/typescript-formatter#10]
It would nice to be able to recursively format a directory.

**Comment by vvakame** [comment]
@pspeter3 in windows?
if you use a Mac OS X or Linux, you can do it now.

```
tsfmt -r lib/**/*.ts
replaced lib/cli.ts
replaced lib/editorconfig.d.ts
replaced lib/formatter.ts
replaced lib/index.ts
replaced lib/provider/base.ts
replaced lib/provider/editorconfig.ts
replaced lib/provider/tslintjson.ts
replaced lib/utils.ts
```

**Comment by pspeter3** [comment]
I'm on OSX. That does not seems to be working for me.

**Comment by vvakame** [comment]
other way, please try `find lib | grep .ts | xargs tsfmt -r` .

**Comment by vvakame** [comment]
in typescript-formatter@1.1.0, filesGlob used from tsconfig.json when exec `tsfmt -r`. #25
