### ISSUE TITLE
'tsfmt' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by GlenQu** [vvakame/typescript-formatter#101]
Hi,

This is probably an easy one.  I am getting the error: 
`'tsfmt' is not recognized as an internal or external command.`

Here are the packages.
```
D:\Users\...\Desktop\quickstart>npm list -g typescript
C:\Users\...\AppData\Roaming\npm
`-- typescript@2.0.6


D:\Users\...\Desktop\quickstart>npm list -g typescript-formatter
C:\Users\...\AppData\Roaming\npm
`-- typescript-formatter@5.2.0
```

When I run `npm install -g typescript-formatter` I get the following warning.
```
npm WARN typescript-formatter@5.2.0 requires a peer of typescript@^2.0.6 || >=2.1.0-dev || >=2.2.0-dev || >=2.3.0-dev but none was installed.
```

New to NPM and not entirely sure where I am going wrong.  Thanks for your help.

**Comment by vvakame** [comment]
it is npm command matter. There is no influence on the operation.
If you want to suppress it, you should exec `npm install -g typescript typescript-formatter`.
