### ISSUE TITLE
TSX support?

### ISSUE THREAD

**Issue by wbhob** [vvakame/typescript-formatter#102]
Does this support tsx? Formatting this block looks funky...
```tsx
    <View style={styles.container}>
        <Text>
            I am a lightbox!
        </Text>
        <TouchableOpacity onPress={this.dismissLightBox.bind(this)}>
            <Text>Close Me!</Text>
        </TouchableOpacity>
      </View>
```

becomes

```tsx
  <View style={ styles.container }>
  <Text>
  I am a lightbox!
    </Text>
    < TouchableOpacity onPress= { this.dismissLightBox.bind(this) } >
      <Text>Close Me!</Text>
        < /TouchableOpacity>
        < /View>
```

**Comment by vvakame** [comment]
I added a test for your issue, but I got other result. https://github.com/vvakame/typescript-formatter/commit/d33dd0f6e18907274fd165648ba9532015cd4905

BTW, tsfmt uses TypeScript Compiler API https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
If you have a formatting style issue when please report it to TypeScript repository.

**Comment by wbhob** [comment]
I'm not writing TSX anymore, but someone else may have this issue. Keep this on your radar.
