### ISSUE TITLE
Formatting fat arrow functions not working correctly

### ISSUE THREAD

**Issue by dominique-mueller** [vvakame/typescript-formatter#106]
The formatting doesn't seem to work correctly for fat arrow functions. For example:

Original code (before formatting):
``` ts
url
  .split( '/' )
  .map( ( urlSegment: string ) => {
    // ...
  } )
  .join( '/' );
```

Formatted code (the result):
``` ts
url
  .split( '/' )
  .map(( urlSegment: string ) => {
    // ...
  } )
  .join( '/' );
```

As one can see, the space between the `map` and the fat arrow function parameter list got removed - although it should not.

My configuration:
``` json
{
  "baseIndentSize": 0,
  "indentSize": 2,
  "tabSize": 2,
  "indentStyle": 2,
  "newLineCharacter": "\r\n",
  "convertTabsToSpaces": true,
  "insertSpaceAfterCommaDelimiter": true,
  "insertSpaceAfterSemicolonInForStatements": true,
  "insertSpaceBeforeAndAfterBinaryOperators": true,
  "insertSpaceAfterConstructor": false,
  "insertSpaceAfterKeywordsInControlFlowStatements": true,
  "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
  "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": true,
  "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": true,
  "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
  "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": true,
  "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": true,
  "insertSpaceAfterTypeAssertion": true,
  "insertSpaceBeforeFunctionParenthesis": false,
  "placeOpenBraceOnNewLineForFunctions": false,
  "placeOpenBraceOnNewLineForControlBlocks": false
}
```

Any option I missed / configured incorrectly?

**Comment by vvakame** [comment]
sorry for late response.
tsfmt uses TypeScript's Compiler API. https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
I have a question. Can you make your request with Visual Studio or Visual Studio Code?

**Comment by dominique-mueller** [comment]
Ah, I just discovered that there is already an open issue for this in the official TypeScript GitHub repository.
Closed as duplicate of https://github.com/Microsoft/TypeScript/issues/15510.

**Comment by vvakame** [comment]
FYI: https://github.com/Microsoft/TypeScript/pull/17394
