### ISSUE TITLE
Formatting multi line object literal

### ISSUE THREAD

**Issue by chamrc** [vvakame/typescript-formatter#107]
Just a quick question how to format multi line object literal?

### Original:
```
await User.update({
email: users[0].email
}, {
permissions: [read._id, write._id]
});
```

### Expected:
```
await User.update({
    email: users[0].email
}, {
    permissions: [read._id, write._id]
});
```

### Actual:
```
await User.update({
    email: users[0].email
}, {
        permissions: [read._id, write._id]
    });
```

**Comment by vvakame** [comment]
sorry for late response.
typescript-formatter uses TypeScript's Compiler API. https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API
Could you report this issue to TypeScript repo?

**Comment by chamrc** [comment]
OK. Thanks.
