### ISSUE TITLE
insertSpaceBeforeTypeAssertion

### ISSUE THREAD

**Issue by mastef** [vvakame/typescript-formatter#108]
Any chance this could be an option?

Similar behaviour to `insertSpaceAfterTypeAssertion`

`function RGBtoHSB( param1: Int, param2: Int, param3: Int )` would become
`function RGBtoHSB( param1 : Int, param2 : Int, param3 : Int )`

**Comment by vvakame** [comment]
Do you want to something like... `insertSpaceBeforeTypeAssertion` ?
It is not implemented in here https://github.com/Microsoft/TypeScript/blob/8fc651870e44efd12598a42ae84fb0e19067fcfd/src/services/types.ts#L563
If you want it, You should open issue on TypeScript repository. 👍

**Comment by mastef** [comment]
Ah, gotcha

**Comment by mastef** [comment]
Good news - it has been now implemented as `insertSpaceBeforeTypeAnnotation` 😄

**Comment by vvakame** [comment]
awesome works! 👏

**Comment by vvakame** [comment]
sorry for late. I just published v7.1.0. please check it!
