### ISSUE TITLE
Add --useVscodeSettings flag just like --useTsconfig and --useTslint

### ISSUE THREAD

**Issue by cspotcode** [vvakame/typescript-formatter#109]
I would like to point tsfmt to a `vscode-recommended-settings.json` and parse it like `.vscode/settings.json`.

I track `vscode-recommended-settings.json` in Git and use it to control tsfmt.  Users can copy it to `.vscode/settings.json` and VSCode will format code in my project's style.

I want to avoid adding `.vscode/settings.json` to Git.  If it's tracked by git and someone wants additional, personal options in `.vscode/settings.json`, git will constantly ask them to commit their changes.   This is why I would like to instead distribute a `vscode-recommended-settings.json`.

I would invoke tsfmt like this:

```
tsfmt --useVscodeSettings ./vscode-recommended-settings.json
```

**Comment by vvakame** [comment]
thanks! 👍
