### ISSUE TITLE
Unclear "Note" section in the readme

### ISSUE THREAD

**Issue by nicholasbishop** [vvakame/typescript-formatter#111]
The readme has a section called "Note" that just says:

> now indentSize parameter is ignored. it is TypeScript compiler matters.

https://github.com/vvakame/typescript-formatter/blob/master/README.md#note

It's not clear to me what that means. I set `indentSize` in my `tsfmt.json` configuration and it was not ignored.

**Comment by vvakame** [comment]
wow, I didn't know that! thanks 👍
