### ISSUE TITLE
Unindent chained methods

### ISSUE THREAD

**Issue by EricChoiKR** [vvakame/typescript-formatter#113]
**Expected:**
```ts
someVar
.chain()
.chain()
```

**Actually:**
```ts
someVar
    .chain()
    .chain()
```

Can I request add option 'Unindent chained methods'?

**Comment by vvakame** [comment]
tsfmt uses [LanguageService API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API).
You can open this request to TypeScript compiler repository. 👍
