### ISSUE TITLE
Do not reformat the file if the newLineCharacter settings is not set

### ISSUE THREAD

**Issue by vegansk** [vvakame/typescript-formatter#114]
The problem is in the line https://github.com/vvakame/typescript-formatter/blob/35c6b6a52307dae014e198acfb985b3c900ca860/lib/index.ts#L166

The file is always reformatting, but what if we just want to preserve file endings? For example we have developers that works on Linux & Windows. And we are using the git setting `git config core.autocrlf true`. And the problem is that `tsfmt --verify` either fails on Windows, or fails on Linux.

**Comment by vvakame** [comment]
thanks!
