### ISSUE TITLE
Typescript - Braces on new line 

### ISSUE THREAD

**Issue by rfossella** [vvakame/typescript-formatter#120]
Hi,
Trying to have the Vscode 'format document' command for Typescript put braces on new line.

Added the following to settings.json with **no** effect.
```
"typescript.format.placeOpenBraceOnNewLineForControlBlocks": true,
"typescript.format.placeOpenBraceOnNewLineForFunctions": true,
```
Is there another setting or file I need to change?

Thanks.
Rob

**Comment by vvakame** [comment]
Hi. What kind of version tsfmt and tsc do you use?

**Comment by rfossella** [comment]
Looks like I have Prettier formatter for Visual Studio Code.

**Comment by vvakame** [comment]
not tsfmt?

**Comment by rfossella** [comment]
I was using the formatter that came with VSCode - typescript formatter, then installed Prettier since it handles multiple formats.

Is there specifically an extension called 'tsfmt' - because I don't see it in extension list.  

Coincidentally, I do use 'phpfmt' where braces work as expected using setting
`"phpfmt.passes": ["AllmanStyleBraces"],`

Thanks for helping.

**Comment by rfossella** [comment]
WHY was this closed?
