### ISSUE TITLE
extends is ignored in tslint.json

### ISSUE THREAD

**Issue by alan-agius4** [vvakame/typescript-formatter#123]
`tslint` rules config from an external `node_modules` are not being parsed by `typescript-formatter`.

Example
```json
{
	"extends": [
		"node_modules/@obg/tools.core/config/tslint.json"
	],
	"rulesDirectory": [
		"@obg/tools.lint-rules",
		"tslint-consistent-codestyle",
		"node_modules/tslint-eslint-rules/dist/rules"
	]
}
```

This won't work due to https://github.com/vvakame/typescript-formatter/blob/master/lib/provider/tslintjson.ts#L49

Ideally for this you use `tslint` API to read the configuration or another way is to use another library that is capable of extends the `json` example https://www.npmjs.com/package/@speedy/json-extends.

I'll happy do a PR with any of them. If you tell me which one you prefer.

**Comment by vvakame** [comment]
sorry for late response.
I'd like to use tslint API pattern.
I want to avoid adding tslint package to `dependencies`.
We should use dynamic import and change makeFormatCodeOptions function signature (return types will change ts.FormatCodeSettings to Promise<ts.FormatCodeSettings>)

```
        const tslint = await import("tslint");
        const config = tslint.Configuration.loadConfigurationFromPath(configFileName!);
        const v = config.rules.get("indent")!;
        // .....
```

**Comment by alan-agius4** [comment]
I’ll look at it when I have some time this week or the next.

Thanks for the feedback though :)
