### ISSUE TITLE
Support for decorators

### ISSUE THREAD

**Issue by Verdier** [vvakame/typescript-formatter#13]
Is there a way to activate support for decorators. Using the latest version of the formatter, I have the following error:
```
     24 |    @MyAnnotation()
             ^ Unexpected '@'.
```

**Comment by vvakame** [comment]
@Verdier what version did you use? I'm using `0.3.2`. it can process decorators. see https://github.com/vvakame/typescript-formatter/commit/bec27f05b80488ea5a43d6923befc20bbea3c842

**Comment by Verdier** [comment]
@vvakame that's true, I'm sorry. I've try with `0.3.1` yesterday... the new version was just published. Thank's for the project! And happy to use decorators with code formatting!

**Comment by vvakame** [comment]
:+1:
