### ISSUE TITLE
Align constructor and function params to have the same indent

### ISSUE THREAD

**Issue by tiberiumihai** [vvakame/typescript-formatter#131]
Is there a way to align the code like this:
```
constructor(private injectableOne: InjectableOne, 
            private injectableTwo: InjectableTwo) { }

updateEntity(name: String, 
             type: String) { }
```
instead of like this:
```
constructor(private injectableOne: InjectableOne, 
  private injectableTwo: InjectableTwo) { }

updateEntity(name: String, 
  type: String) { }
```
?

**Comment by vvakame** [comment]
sorry for late response.
tsfmt use a [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview).
Please file this issue to [TypeScript repository](https://github.com/Microsoft/TypeScript)!

**Comment by tiberiumihai** [comment]
Thanks. Can be tracked here: https://github.com/Microsoft/TypeScript/issues/11629
