### ISSUE TITLE
Support for JSX?

### ISSUE THREAD

**Issue by myitcv** [vvakame/typescript-formatter#18]
JSX support has landed:

https://github.com/Microsoft/TypeScript/pull/3564

Any plans to support that here?

Thanks

**Comment by vvakame** [comment]
@myitcv tsfmt use typescript that are installed at the same time.
please check this sample https://gist.github.com/vvakame/9a6459464258c7de63f9

**Comment by myitcv** [comment]
Thanks, I think I've tracked down the problem. Confirmed that JSX formatting is working, except (for some reason) for the following:

```typescript
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
    return <span>This is a test</span>;
}
```

produces:

```
/// <reference path="typings/tsd.d.ts" />

import React = require("react");

function test(): any {
    return <span>This is a test< /span>;
}

```

Notice the problematic `< /span>`.

The former compiles, the latter does not:

```
$ ./node_modules/.bin/tsc --jsx react --module system test.tsx
test.tsx(6,34): error TS1003: Identifier expected.
test.tsx(6,35): error TS1005: '>' expected.
test.tsx(9,1): error TS17002: Expected corresponding JSX closing tag for 'span'.
```

So this is probably a TypeScript core thing?

**Comment by vvakame** [comment]
yes. typescript-formatter depends to TypeScript core.
typescript-formatter can consume code same as tsc command.
I'm not JSX user. but I think `<     /span>` is broken syntax.

**Comment by myitcv** [comment]
Thanks. I'll raise this as an issue over [there](https://github.com/Microsoft/TypeScript) and cc you

**Comment by myitcv** [comment]
Reference https://github.com/Microsoft/TypeScript/issues/4127

**Comment by myitcv** [comment]
@vvakame - please see https://github.com/Microsoft/TypeScript/issues/4127#issuecomment-127329709

**Comment by myitcv** [comment]
I've just raised #19 to flesh out a fix for this

**Comment by vvakame** [comment]
typescript-formatter 1.0.0 support jsx maybe i think so...

**Comment by myitcv** [comment]
It does, thanks
