### ISSUE TITLE
Pass in the tsfmt options via an object

### ISSUE THREAD

**Issue by slavik925** [vvakame/typescript-formatter#23]
Here is a common situation when working on a large project that contains many repos, but they are all sharing the same formatting style file. In this case to make the typescript-formatter work each repo requires it's own copy of the tsfmt.json, etc.

Could it be possible to add a method that allowed for the consumer to pass in the tsfmt options via an object?

**Comment by vvakame** [comment]
um? Let me clarify my understanding.
you want to use `tsfmt --configDir ../rootRepo ./**/*.ts` style?

**Comment by slavik925** [comment]
Yes, but the config not necessary to be in the .ts file. It could be even enough just to specify **configDir** where for example _tsfmt.json_ will be lie. 

I think the good place for adding this will be `interface Options`.

Here is the way how we will be using this **baseDir** property in the grunt plugin to pass it into processFiles function.

![zrzut_ekranu_091815_043014_pm](https://cloud.githubusercontent.com/assets/574076/9961748/8bbbaff6-5e22-11e5-850d-ce9bf2c48f9d.jpg)

**Comment by vvakame** [comment]
add `--baseDir` options and `baseDir` property for Option interface :+1:

**Comment by slavik925** [comment]
Thank you! This is really very helpful.
