### ISSUE TITLE
JSX closing nodes aren't indented well

### ISSUE THREAD

**Issue by alexgorbatchev** [vvakame/typescript-formatter#29]
formatting

```js
export default class Application extends React.Component<any, any> {
  render() {
    return (
      <div>
        <Component name="World" kind={ComponentKind.warning} />
      </div>
    );
  }
}
```

results in

```js
export default class Application extends React.Component<any, any> {
  render() {
    return (
      <div>
        <Component name="World" kind={ComponentKind.warning} />
        </div>
    );
  }
}
```

Same deal with all other closing nodes when they are on separate lines

**Comment by vvakame** [comment]
what version of tsc do you use?
almost code formatting issue is refer to typescript.
typescript-formatter is pass through format options to typescript compiler. https://github.com/vvakame/typescript-formatter/blob/master/lib/formatter.ts#L18

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript/issues/3838 ?

**Comment by alexgorbatchev** [comment]
tsc 1.6 . Could you help me understand why formatting issues refer to `typescript` and not `typescript-formatter`? Microsoft/TypeScript#3838 does look like the same issue, thank you!
