### ISSUE TITLE
More aggressive edits

### ISSUE THREAD

**Issue by felixSchl** [vvakame/typescript-formatter#32]
What would it take to get more aggressive edits? I am thinking gofmt here, which slices and dices my file to it's liking, reshuffling imports and re-arranging things as it pleases.

Consider what `tsfmt` does to this:

```typescript
export
default
class
Provider
{
constructor (

) {}
}
```

becomes:

```typescript
export
  default
  class
  Provider {
  constructor (

  ) { }
}
```

but ideally, would be:

```typescript
export default class Provider {
  constructor() {
  }
}
```

To be honest I don't know how feasible this would end up being with a language like typescript, but seems like something worth exploring. So instead of making edits as such to a document, you read the entire document into it's canonical AST, and then generate the source code for the AST. That's what's so great about `gofmt` - you don't worry about editing text as much, you worry about shaping the AST. Another example is `paredit` for emacs for editing lisp code. I found both experiences extremely great to work with.

Is this something that can be done in this project or would it be more of a typescript repo level issue? I see in the sources most of the code is concerned with the wrapping for `formatting.formatDocument`.

Thanks for your time

**Comment by myitcv** [comment]
@felixSchl - I'll leave @vvakame to answer on behalf of the project but here are my thoughts. I too come from a Go background so have a similar starting point with `gofmt`. Things like re-ordering imports etc could, as far as I understand things, be achieved by extending this project, `tsfmt`.

The one important distinction here with `gofmt` is that (unfortunately, in my opinion) one can supply formatting options. The superset of these formatting options is defined in the TypeScript services 'layer' (part of the core TypeScript project). 

As it stands this project simply acts as a simple formatter with the key distinction being that it first computes a 'union' of formatting options from:

* `tsfmt.json`
* `.editorconfig`
* `tslint.json` (equivalent to `go vet` in many respects)
* `tsconfig.json` (the compiler options)

Hence once this tool has computed the 'union' of required options it then simply delegates to the TypeScript services layer to format the AST.

There is nothing to my knowledge that would fundamentally prevent this tool being adapted to the following flow:

1. Parse document to AST
2. Reorder, munge etc AST (e.g. adjusting imports)
3. Compute formatting options (status quo)
4. Format AST based on formatting options
5. Output to `stdout` (again, status quo on various output options)

We already rely on `tsfmt` to enforce that all of our code is automatically formatted in a consistent way (much like Go projects do with `gofmt`). If `tsfmt` were extended in much the same way that [`goimports`](https://godoc.org/golang.org/x/tools/cmd/goimports) extends `gofmt` then we would certainly find a use for this.

**Comment by vvakame** [comment]
thank you for your request. 
tsfmt glue the TypeScript's formatter to users. that is all.

But I think your opinion is very useful. :+1: 
You should open issue to TypeScript repo.
