### ISSUE TITLE
Multi-line import statements not handled properly

### ISSUE THREAD

**Issue by aeisenberg** [vvakame/typescript-formatter#33]
This seems wrong to me. If I have an import statement that is split into multiple lines like this:

```
import {ReadStream, WriteStream}
  from 'fs';
```
tsfmt will un-indent the `from` expression. The result is this:
```
import {ReadStream, WriteStream}
from 'fs';
```
Whereas, it seems like the result should be unchanged.

**Comment by vvakame** [comment]
This is default behavior in TypeScript language service.
http://goo.gl/yGImmy `right click -> Format Code`.

You should open same issue in https://github.com/Microsoft/TypeScript/issues .
Good luck!

**Comment by aeisenberg** [comment]
Done. https://github.com/Microsoft/TypeScript/issues/6924
