### ISSUE TITLE
Update TypeScript Dep to 1.8.x

### ISSUE THREAD

**Issue by Paden** [vvakame/typescript-formatter#35]
Hey everyone, 

I maintain a [grunt plugin]([https://github.com/Paden/grunt-tsfmt]) that uses tsfmt. It would be great if we could update the typescript dependency to 1.8.x. See https://github.com/Microsoft/TypeScript for the latest 1.8.x release.

Thanks!

**Comment by cjlpowers** [comment]
+1

**Comment by myitcv** [comment]
TypeScript is a [`peerDependency`](https://github.com/vvakame/typescript-formatter/blob/master/package.json#L38-L40) - does this not satisfy your requirements?

**Comment by dvalys** [comment]
+1

**Comment by vvakame** [comment]
Oh, I forgot it. thanks :+1: 
I'll working tonight (JST).

**Comment by vvakame** [comment]
2.1.0 released. add `insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces` options.

**Comment by Paden** [comment]
@vvakame thank you!
