### ISSUE TITLE
Any license declaration?

### ISSUE THREAD

**Issue by estorski** [vvakame/typescript-formatter#40]
Hey there,

I'm wondering what's the license on this, can I integrate this into a commercial project pipeline?

**Comment by vvakame** [comment]
this tool is MIT license. http://googleresearch.blogspot.jp/2016/05/announcing-syntaxnet-worlds-most.html
And I pushed [LICENSE.txt](https://github.com/vvakame/typescript-formatter/commit/539b71bfd99934980861352f4789a0c2c350baa1)
