### ISSUE TITLE
Error reading tslint.json

### ISSUE THREAD

**Issue by estorski** [vvakame/typescript-formatter#41]
1) Make sure you have `tslint.json` in a folder with your typescript file;
2) Make sure you have a comment inside that `tslint.json`, like this: 
```
    "one-line": [
      true,
      //"check-open-brace",
      "check-whitespace"
    ],
```
3) Run `tsfmt` against your typescript. Actual result: an exception starting with
```
SyntaxError: Unexpected token /
    at Object.parse (native)
    at Object.makeFormatCodeOptions [as default] (C:\Users\Kostia\AppData\Roaming\npm\node_modules\typescript-formatter\lib\provider\tslintjson.js:15:23)
    at processString (C:\Users\Kostia\AppData\Roaming\npm\node_modules\typescript-formatter\lib\index.js:65:49)
```

4) Try to wipe the comment completely out - everything works OK;

**Comment by vvakame** [comment]
JSON format is not permit comment.
tslint is not permit it too.
I think it is no need to support it.

**Comment by aleung** [comment]
JSON comment was supported in tslint [3.8.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v380-dev0):

> [enhancement] Comments now allowed in tslint.json files (#1129)

**Comment by vvakame** [comment]
@aleung 5a4fdfd118b9c1572d618d96c9b0b76ddaa074d9 . this commit will release at same timing of TypeScript 2.0.1 release
