### ISSUE TITLE
Lint "indent": [ true,"tabs"] is not respected

### ISSUE THREAD

**Issue by estorski** [vvakame/typescript-formatter#42]
Currently there's an issue that if I use tabs on the project, and have a `tslint`config having this specified, this does not get catered by `tsfmt`.
It does have the `ConvertTabsToSpaces` setting turned on by default, and the only way (as I see it) to turn it off is only by using `editorconfig`.

**Comment by vvakame** [comment]
thank you for your report!
I'll fix it.

**Comment by vvakame** [comment]
v2.2.0 released.
