### ISSUE TITLE
Is there the "right" way to extend the tool with custom formatters?

### ISSUE THREAD

**Issue by estorski** [vvakame/typescript-formatter#43]

**Comment by vvakame** [comment]
https://github.com/vvakame/typescript-formatter/blob/539b71bfd99934980861352f4789a0c2c350baa1/lib/formatter.ts#L18
tsfmt is very thin wrapper of [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API).
If you want to extend formatter, You should extends language servise.

**Comment by estorski** [comment]
@vvakame 
What do you think, is this project (`ts-fmt`) an appropriate place to provide an API to writing custom formatters (which actually make use of the TS Language Services in order to walk by the code files object model, and reformat it when necessary) ?
An example of such a formatter could be - a formatter which makes sure that all `export` statements go in the very end of a file.

**Comment by vvakame** [comment]
@estorski I don't do that. I want to keep thin wrapper of language service. but if you send a pull request, I will merge that it is small and maintainable structure.
