### ISSUE TITLE
Format HTML in templates strings? 

### ISSUE THREAD

**Issue by mhartington** [vvakame/typescript-formatter#45]
Is it possible to not only format actual code, but html that could be in multi-line template strings? For example

```typescript

let message = `
<div>
  <h1>There was an error
  <p> the error was ${errMsg}</p>
</div>
`
````

**Comment by vvakame** [comment]
tsfmt use a [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview).
I do not do things that can not be language service.
