### ISSUE TITLE
tsfmt does not recognize exclude in tsconfig.json

### ISSUE THREAD

**Issue by redhatlinux10** [vvakame/typescript-formatter#48]
tsfmt recognizes `files`, `filesGlob` in `tsconfig.json` and works well , but not `exclude`
tsfmt :2.2.1

**Comment by vvakame** [comment]
NOTE https://github.com/Microsoft/TypeScript/issues/1927

**Comment by vvakame** [comment]
I'll do this. but PR welcome!

**Comment by vvakame** [comment]
waiting for TypeScript 2.0.1 release.

**Comment by vvakame** [comment]
https://github.com/Microsoft/TypeScript/milestone/24
umm...

**Comment by vvakame** [comment]
I just released typescript-formatter v3.0.0. try with `npm install typescript-formatter@next`
