### ISSUE TITLE
tsfmt does not distinguish union type | from binary operator |

### ISSUE THREAD

**Issue by elseorand** [vvakame/typescript-formatter#49]

**Comment by vvakame** [comment]
What is the problem?

BTW.
tsfmt using [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API).
https://github.com/vvakame/typescript-formatter/blob/master/lib/formatter.ts#L14-L21
not implimented own formatting pattern.
I recommend your request send to [TypeScript repo](https://github.com/Microsoft/TypeScript). 😉
