### ISSUE TITLE
tsfmt doesn't support include in tsconfig.json

### ISSUE THREAD

**Issue by aleung** [vvakame/typescript-formatter#50]
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#glob-support-in-tsconfigjson

**Comment by vvakame** [comment]
#48 duplicated
It implemented already in https://github.com/vvakame/typescript-formatter/tree/tsc-2.0 branch.
I'm waiting for TypeScript 2.0.0 stable release.
