### ISSUE TITLE
Use in a node script

### ISSUE THREAD

**Issue by DrMabuse23** [vvakame/typescript-formatter#52]
Hi iam building a cli on my company and i have a question is it possible to use your module in a node script without exec ?

thx

**Comment by DrMabuse23** [comment]
ok i see the example ^^

**Comment by vvakame** [comment]
and, check lib/cli.ts :+1:

**Comment by DrMabuse23** [comment]
hey thx for module and thx for info 💯

**Comment by no-more** [comment]
Hi, I'm trying to achieve the same thing, do you have a working example please ?

thanks.
