### ISSUE TITLE
Wrong indentation when 2 objects are passed as function parameters.

### ISSUE THREAD

**Issue by radarsu** [vvakame/typescript-formatter#53]
Wrong indentation when 2 objects are passed as function parameters.

How it should look
```
User.update({
    id: user.id,
}, {
    test: "test",
});
```
How it actually looks:
```
User.update({
    id: user.id,
}, {
        test: "test",
    });
```

**Comment by vvakame** [comment]
tsfmt use a [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview).
I do not do it if language service can not do that.
