### ISSUE TITLE
Please add documentation about the proper location av config files.

### ISSUE THREAD

**Issue by oivvio** [vvakame/typescript-formatter#57]
I'd just like to know in what locations tsfmt will look for tsfmt.json, .editorconfig and tslint.json

**Comment by vvakame** [comment]
Is this not enough for you? https://www.npmjs.com/package/typescript-formatter#read-settings-rules

**Comment by oivvio** [comment]
Ah. Sorry I didn't parse that. Two follow up questions?

1. When tsfmt reads more then one ruleset, which rules gets precedence in
the event of a conflict?

2. Is there a setting for correctly indenting tsx?

**Comment by vvakame** [comment]
> 1. When tsfmt reads more then one ruleset, which rules gets precedence in
the event of a conflict?

tsfmt.json > tsconfig.json > editorconfig > tslint.json
The rules gathering per files.
foo/bar/buzz.ts and foo/fuga/piyo.ts are not formatting by same ruleset.

> 2. Is there a setting for correctly indenting tsx?

Maybe yes. I don't using tsx. but it can consumed by TypeScript Language Service.
