### ISSUE TITLE
Formatter + TypeScript 2 now adds spaces in the imports

### ISSUE THREAD

**Issue by jvanoostveen** [vvakame/typescript-formatter#58]
Using the same settings, when I format with pre TS 2, the import statements don't have any spaces:
```
import {foo} from 'bar';
```

When I update to TypeScript 2 and keep the formatting settings as is, and do another format, the import statements are redone with spaces:
```
import { foo } from 'bar;
```

Not sure if a bug is fixed or new. We can reformat the entire project of course, but I would rather not do it because it would also is a source for (simple, but annoying) conflicts this way.

I've also tried playing with the `insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis` setting, but that doesn't change the behavior at all.

**Comment by vvakame** [comment]
tsfmt using [TypeScript Language Service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#pretty-printer-using-the-ls-formatter).
I think it is default behaviour of tsc 2.0.
