### ISSUE TITLE
Make it possible to specify the `tsconfig.json`

### ISSUE THREAD

**Issue by endel** [vvakame/typescript-formatter#67]
Would be great to allow to specify a different `tsconfig.json` file to use.

A practical example is that our `tsconfig.json` doesn't include the test files. We have a different `tsconfig.test.json`, which do include them.

Given this scenario, it might make sense to either allow to specify a different `tsconfig.json` file to use, or allow a `"files"` key in the `tsfmt.json`.

What's your thoughts about this? 
Cheers!

**Comment by lpicquet** [comment]
I have something similar. I'd like for us to be able to specify which file I use for the configuration of tsfmt.
please consider adding a "-c" or "--config" parameter.
