### ISSUE TITLE
A possible problem with spaces in parens

### ISSUE THREAD

**Issue by prettydiff** [vvakame/typescript-formatter#69]
https://github.com/Glavin001/atom-beautify/issues/1362#issuecomment-261438930 and https://gist.github.com/anonymous/4d5e96af5001ad3a6c1f6015bc3e61ab

**Comment by vvakame** [comment]
tsfmt use a [TypeScript language service](https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview).
Please report it to the TypeScript repository.
