### ISSUE TITLE
DTS file no longer included

### ISSUE THREAD

**Issue by pspeter3** [vvakame/typescript-formatter#7]
There used to be a dts file but it is no longer provided

**Comment by vvakame** [comment]
@pspeter3 0.2.1 released!
https://github.com/vvakame/typescript-formatter/blob/master/typescript-formatter.d.ts

**Comment by pspeter3** [comment]
Thanks!

**Comment by pspeter3** [comment]
The problem with this is that the dts files is for `tsfmt` but the node modules is `typescript-formatter`

**Comment by vvakame** [comment]
oops, sorry.
I'll fix it. please wait.

**Comment by vvakame** [comment]
@pspeter3 0.2.2 released. sorry!

**Comment by pspeter3** [comment]
Hooray! Thank you! :smile:
