### ISSUE TITLE
unmet perr-dependency when Installing typescript version globally

### ISSUE THREAD

**Issue by andru255** [vvakame/typescript-formatter#71]
When I run this command in a terminal:

`sudo npm install -g typescript`

The current typescript version is 2.1.5.

Then:

`sudo npm install -g typescript-formatter`

Finally, shows me:

UNMET PEER DEPENDENCY typescript@^2.0.6 || >=2.1.0-dev || >=2.2.0-dev
└── typescript-formatter@4.0.1

**Comment by vvakame** [comment]
could you try `npm install -g typescript typescript-formatter` ?

**Comment by andru255** [comment]
@vvakame it works! thanks you, I though it was for some feature for a new typescript release, but works perfect.
