### ISSUE TITLE
Support for using tabs for indentation

### ISSUE THREAD

**Issue by hachre** [vvakame/typescript-formatter#8]
It would be nice to get a indent-with-tabs mode. Also in .editorconfig when you have "indent_style = tab" set it should infer 1 tab per indentation level without giving a tab_width parameter.

**Comment by hachre** [comment]
I looked at your code and saw that you are using the TypeScript formatter so I opened a bug with them:
https://github.com/Microsoft/TypeScript/issues/2306

**Comment by vvakame** [comment]
thanks!
