### ISSUE TITLE
Breaking change for vscode in options

### ISSUE THREAD

**Issue by Dirrk** [vvakame/typescript-formatter#87]
This line change is breaking: https://github.com/vvakame/typescript-formatter/commit/2d9fbed466516e1c7be7fe9f5dc321e340484f42#diff-13b5b151431c7e7a17f273559ed212d5R24

This is the default options interface that is exposed to all of the consuming libraries.  Most libraries did not add vscode to their options and its at least breaking one build.  I am creating a PR for this now.

**Comment by vvakame** [comment]
thanks! I just released v4.2.2.
