### ISSUE TITLE
useTsconfig option is ignored

### ISSUE THREAD

**Issue by yshrsmz** [vvakame/typescript-formatter#90]
as title says, when I execute command like `tsfmt -r --useTsconfig=./tsconfig.main.json`, tsfmt print out help messages and doesn't do anything.

And after some debugging, it seems like the condition in this line becomes true with the command I use.

https://github.com/vvakame/typescript-formatter/blob/5edfef9609f8a3d28135668f0141f1828916364b/lib/cli.ts#L90

**Comment by vvakame** [comment]
thank you for reporting!
I just published v5.1.2.

**Comment by yshrsmz** [comment]
Thanks for the quick fix!
It's now working :)
