### ISSUE TITLE
Some options are unknown in .vscode/settings.json

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [vvakame/typescript-formatter#97]
When I configure typescript-formatter via the settings.json I get a message that some settings are unknown. The missing options are:

typescript.format.insertSpaceAfterConstructor
typescript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces

![screenshot](http://i.imgur.com/vcsKFOb.png)

I am using vscode 1.9.1.

**Comment by vvakame** [comment]
It is from here.
https://github.com/Microsoft/TypeScript/blob/88ac7dfdc7aac9614e94415eccabf77596daaddc/lib/typescript.d.ts#L3580-L3596

You can report this issue to https://github.com/Microsoft/vscode 😉
